# Site settings ...
uri: menecio.me
url: https://menecio.me
name: Aristobulo Meneses
title: menecio
email: aristobulo@menecio.me
author: menecio
baseurl: ""
keywords: "python,django,developer,backend,django-rest-framework,drf"
description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione nihil, velit odio quia autem quos. Natus itaque sint, nisi fuga dolorum. Iste ea cumque, aliquam dignissimos vitae labore atque minima?"
social_username: menecio

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
