# Site settings ...
uri: menecio.me
url: https://menecio.me
name: Aristobulo Meneses
title: menecio
email: aristobulo@menecio.me
author: menecio
baseurl: ""
keywords: "python,django,developer,backend,django-rest-framework,drf,menecio"
description: "Hi I'm Aristobulo (a.k.a menecio), I <3 writting things (that might work) in Python, and this is my blog."
social_username: menecio

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
